name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t jesusalonso/react-test -f ./client/Dockerfile.dev ./client
    - run: docker run -e CI=true jesusalonso/react-test npm test

    - run: docker build -t jesusalonso/multi-client ./client
    - run: docker build -t jesusalonso/multi-nginx ./nginx
    - run: docker build -t jesusalonso/multi-server ./server
    - run: docker build -t jesusalonso/multi-worker ./worker

    - run: docker push jesusalonso/multi-client
    - run: docker push jesusalonso/multi-nginx
    - run: docker push jesusalonso/multi-server
    - run: docker push jesusalonso/multi-worker
